### ISSUE TITLE
Klov support not working for extentreports 4

### ISSUE THREAD

**Issue by thomasdeurloo** [email2vimalraj/CucumberExtentReporter#108]
Hi!

I had it working with Klov using the setup in the example (with ExtentProperties.INSTANCE), using version 3.1.1 with extent reports version 3.1.1 and 3.1.5. Now we switched to extentreports version 4 (version 4.0.9) because of several fixes and improvements, which works fine with the cucumber extent reporter itself. But when using Klov it throws a NoClassDefFoundError because in version 4 the KlovReporter does not exists (has been changed to ExtentKlovReporter, i guess)

Can you get the Klov support working again in combination with extentreports 4?
Thanks!

```
cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/KlovReporter
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:114)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:245)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:291)
	at com.sun.proxy.$Proxy11.done(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.done(JUnitReporter.java:227)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:101)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by thomasdeurloo** [comment]
I think i got it working locally by replacing KlovReporter with ExtentKlovReporter, so that should fix it. 
But it does not pass tag/category information correctly to Klov. I can't figure that out.

> Hi!
> 
> I had it working with Klov using the setup in the example (with ExtentProperties.INSTANCE), using version 3.1.1 with extent reports version 3.1.1 and 3.1.5. Now we switched to extentreports version 4 (version 4.0.9) because of several fixes and improvements, which works fine with the cucumber extent reporter itself. But when using Klov it throws a NoClassDefFoundError because in version 4 the KlovReporter does not exists (has been changed to ExtentKlovReporter, i guess)
> 
> Can you get the Klov support working again in combination with extentreports 4?
> Thanks!
> 
> ```
> cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/KlovReporter
> 	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:114)
> 	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)
> 	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:245)
> 	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:291)
> 	at com.sun.proxy.$Proxy11.done(Unknown Source)
> 	at cucumber.runtime.junit.JUnitReporter.done(JUnitReporter.java:227)
> 	at cucumber.api.junit.Cucumber.run(Cucumber.java:101)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> ```


I think i got it working locally by replacing KlovReporter with ExtentKlovReporter, so that should fix it. 
But it does not pass tag/category information correctly to Klov. I can't figure that out.
