### ISSUE TITLE
java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ExtentHtmlReporter

### ISSUE THREAD

**Issue by KonkaKrish** [email2vimalraj/CucumberExtentReporter#121]
>### Getting Below error, please help me guys spent a lot of time to fix this issue and no luck so far 
>Not getting extent reports - tried many ways and got struck, provided below my POM.xml and runner file- much appreciate your help in advance!
**************************************************************************

FAILED CONFIGURATION: @AfterClass extentReport
java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ExtentHtmlReporter
	at com.cucumber.listener.Reporter.loadXMLConfig(Reporter.java:56)
	at com.API.runner.CucumberRunner.extentReport(CucumberRunner.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.ClassNotFoundException: com.aventstack.extentreports.reporter.ExtentHtmlReporter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 more #

**My POM.xml**
**-----------------**
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Cucumber_API</groupId>
  <artifactId>Cucumber_API</artifactId>
  <version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>4.0.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>4.0.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>4.0.1</version>
		</dependency>

		
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>4.1.2</version>
		</dependency>

		
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.0.6</version>
		</dependency>

		<dependency>
    		<groupId>com.relevantcodes</groupId>
    		<artifactId>extentreports</artifactId>
    		<version>2.41.2</version>
		</dependency>
		
		
		<dependency>
		    <groupId>com.vimalselvam</groupId>
		    <artifactId>cucumber-extentsreport</artifactId>
		    <version>3.1.1</version>
		</dependency>
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>1.2.6</version>
		</dependency>

		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>5.4.0</version>
		</dependency>

		
		<dependency>
		    <groupId>info.cukes</groupId>
		    <artifactId>cucumber-java</artifactId>
		    <version>1.2.6</version>
		    <type>pom</type>
		</dependency>

		<dependency>
		    <groupId>info.cukes</groupId>
		    <artifactId>cucumber-jvm-deps</artifactId>
		    <version>1.0.5</version>
		    <scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>1.2.6</version>
		</dependency>

		<dependency>
		    <groupId>info.cukes</groupId>
		    <artifactId>cucumber-junit</artifactId>
		    <version>1.2.6</version>
		</dependency>

	</dependencies>

</project>

**Runner.Java**
**-----------------**
	import java.io.File;
	import org.testng.annotations.AfterClass;
	import com.API.report.reportHelp;
	import com.cucumber.listener.Reporter;
	import cucumber.api.CucumberOptions;
	import cucumber.api.testng.AbstractTestNGCucumberTests;
	
	@CucumberOptions(strict = true, monochrome = true, features = "src/test/resources/features", glue = "com.API.StepDef", plugin = {
			"pretty", "json:target/cucumber.json","com.cucumber.listener.ExtentCucumberFormatter:target/cucumber-reports/report.html"})
	
	public class CucumberRunner extends AbstractTestNGCucumberTests {

	
		@AfterClass(alwaysRun = true)
		public void extentReport() throws Exception {
			Reporter.loadXMLConfig(new File("src/test/resources/extent-config.xml"));

	        
		}

	}

**Comment by StefaneAL** [comment]
What if you try to use
` "com.vimalselvam.cucumber.listener.ExtentCucumberFormatter:target/cucumber-reports/report.html" 
`
instead of
`"com.cucumber.listener.ExtentCucumberFormatter:target/cucumber-reports/report.html"
`

assuming that 
```
<dependency>
	    <groupId>com.vimalselvam</groupId>
	    <artifactId>cucumber-extentsreport</artifactId>
	    <version>3.1.1</version>
	</dependency>
```
