### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by sramasetty** [email2vimalraj/CucumberExtentReporter#16]
I'm getting NullPointerException and below are the stack trace

java.lang.NullPointerException
	at com.cucumber.listener.ExtentCucumberFormatter.close(ExtentCucumberFormatter.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy14.close(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.close(JUnitReporter.java:213)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)

**Comment by email2vimalraj** [comment]
@sramasetty : Kindly share your test if possible.

**Comment by sramasetty** [comment]
Here is my Runner
===============
package com.cucumberexamples.stepdefs;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(

        features = "src/test/resources/features",
        format = {"json:target/integration_cucumber.json"},
        plugin = {"com.cucumber.listener.ExtentCucumberFormatter:output/report.html"}
        )
public class RunTest {
}

**Comment by email2vimalraj** [comment]
Make sure you have the below `@BeforeClass` at your runner class as mentioned in the readme instruction (https://github.com/email2vimalraj/CucumberExtentReporter/blob/master/Readme.md). This was the new change done on v1.1.0 to make the library more stable and to incorporate the system informations:

```
    @BeforeClass
    public static void setup() {
        ExtentCucumberFormatter.initiateExtentCucumberFormatter();
        ExtentCucumberFormatter.loadConfig(new File("src/test/resources/extent-config.xml"));

        ExtentCucumberFormatter.addSystemInfo("Browser Name", "Firefox");
        ExtentCucumberFormatter.addSystemInfo("Browser version", "v31.0");
        ExtentCucumberFormatter.addSystemInfo("Selenium version", "v2.53.0");

        Map systemInfo = new HashMap();
        systemInfo.put("Cucumber version", "v1.2.3");
        systemInfo.put("Extent Cucumber Reporter version", "v1.1.0");
        ExtentCucumberFormatter.addSystemInfo(systemInfo);
    }
```

Kindly re-open if you still face the issue.

**Comment by DoulatRana** [comment]
Hi Vimal, I'm getting this issue. Here is my runner program


import java.io.File;
import java.util.HashMap;
import java.util.Map;
import org.junit.runner.RunWith;
import org.testng.annotations.BeforeClass;
import com.cucumber.listener.ExtentCucumberFormatter;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(features={"src/features"},
glue={"steps"},

tags={"@sanity,@prod"},
plugin = {"pretty","html:target/cucumber","com.cucumber.listener.ExtentCucumberFormatter"})
public class RunCukes //extends AbstractTestNGCucumberTests
{
	  
	@BeforeClass
    public static void setup() 
	{
      ExtentCucumberFormatter.initiateExtentCucumberFormatter();
     
      ExtentCucumberFormatter.loadConfig(new File("src/extent-config.xml"));

      // User can add the system information as follows
      ExtentCucumberFormatter.addSystemInfo("Browser Name", "Firefox");
      ExtentCucumberFormatter.addSystemInfo("Browser version", "v50.0");
      ExtentCucumberFormatter.addSystemInfo("Selenium version", "v3.0.1");
      
      Map systemInfo = new HashMap();
      systemInfo.put("Cucumber version", "v1.2.5");
      systemInfo.put("Extent Cucumber Reporter version", "v1.1.1");
      ExtentCucumberFormatter.addSystemInfo(systemInfo);
     }
}

**Comment by DoulatRana** [comment]
I'm getting following error
java.lang.NullPointerException
	at com.cucumber.listener.ExtentCucumberFormatter.close(ExtentCucumberFormatter.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
	at com.sun.proxy.$Proxy15.close(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.close(JUnitReporter.java:232)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:102)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
