### ISSUE TITLE
java.lang.NoClassDefFoundError: com/relevantcodes/extentreports/ExtentReports

### ISSUE THREAD

**Issue by TanmoyNandy** [email2vimalraj/CucumberExtentReporter#20]
Hi,

I have a cucumber-selenium project. I've added the extentReports v1.1.0 jar file. But while executing, I'm getting the below error. Pls help.

java.lang.NoClassDefFoundError: com/relevantcodes/extentreports/ExtentReports
	at com.cucumber.listener.ExtentCucumberFormatter.close(ExtentCucumberFormatter.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy15.close(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.close(JUnitReporter.java:213)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

Please find my code in the attached file.
[ExtentReports.zip](https://github.com/email2vimalraj/CucumberExtentReporter/files/426384/ExtentReports.zip)

**Comment by Manasaanand** [comment]
HI Selva,

Is there any solution to this problem?
I am unable to come out of it. Even though reporting structure is good, I am unable to make  use of it.
Looking forward to hear from you

**Comment by email2vimalraj** [comment]
I see you just attached the runner java class. It would be great if you could attach the `pom` file, if possible a sample project.

**Comment by anshooarora** [comment]
> I have a cucumber-selenium project. I've added the extentReports v1.1.0 jar file. But while executing, I'm getting the below error. Pls help.

PS.  Do not add further dependencies.  

Also,  version 1 is no longer supported.

**Comment by Manasaanand** [comment]
@email2vimalraj 

PFA

**Comment by email2vimalraj** [comment]
@Manasaanand : I don't see you have added the dependency for **cucumber-extentsreport**. That is the reason you are getting **class not found** exception. Add the dependency as follows:

```
<dependency>
    <groupId>com.vimalselvam</groupId>
    <artifactId>cucumber-extentsreport</artifactId>
    <version>1.1.1</version>
</dependency>
```

Closing this ticket. Feel free to re-open in case you are facing the issue after adding the dependency.

**Comment by email2vimalraj** [comment]
@anshooarora : I guess he meant the version of `cucumber-extentsreport`.
