### ISSUE TITLE
Missing class com.aventstack.extentreports.gherkin.model.Angenommen

### ISSUE THREAD

**Issue by buekera** [email2vimalraj/CucumberExtentReporter#58]
I just updated to version 3.0.1 and ExtentReport 3.0.6 and suddenly get an error.

I need to point out that I'm using the german classes for implementing the steps. That's why the missing class is "Angenommen", which means "Given".

I'm aware that the error may not have anything to do with your work @email2vimalraj but I'd like to post it anyway.

Here the full stacktrace:

```
java.lang.ClassNotFoundException: com.aventstack.extentreports.gherkin.model.Angenommen
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.aventstack.extentreports.GherkinKeyword.<init>(GherkinKeyword.java:46)
	at com.cucumber.listener.ExtentCucumberFormatter.match(ExtentCucumberFormatter.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy6.match(Unknown Source)
	at cucumber.runtime.Runtime.runStep(Runtime.java:278)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:121)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
Exception in thread "main" java.lang.NullPointerException
	at com.cucumber.listener.ExtentCucumberFormatter.result(ExtentCucumberFormatter.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy6.result(Unknown Source)
	at cucumber.runtime.Runtime.runStep(Runtime.java:309)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:121)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
```

**Comment by anshooarora** [comment]
We can introduce a mapper in the API which would allow you to use different languages with the existing classes (And, Given) etc. I will share a sample soon.

**Comment by anshooarora** [comment]
We can base the mapper to 

https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json

**Comment by anshooarora** [comment]
Hello.  Can you please test with this branch:  https://github.com/anshooarora/extentreports-java/tree/cucumber-spoken-languages?  You will have to add the below statement to your setup:

```
extent.setGherkinDialect("de");
```

**Comment by buekera** [comment]
I will test it today, thanks alot!

**Comment by buekera** [comment]
Hey @anshooarora , I finally have time to look into this issue.
How do I test this specific branch in my gradle setup?

**Comment by anshooarora** [comment]
This issue is now fixed and will be part of 3.0.7.   The release should be available in nexus/maven/gradle in the next hour or so.  I will update the documentation and changelog tonight.

**Comment by buekera** [comment]
Cool, sounds very promising! Thanks for taking care about this kind of _niche_ issue!

**Comment by buekera** [comment]
Thanks, everything is working as intended now! :+1:

**Comment by thomasdeurloo** [comment]
Hi, Gherkin also supports an asterisk "*" to use as a keyword instead of given,when,then. But when i use the asterisk i get te same error:

java.lang.ClassNotFoundException: com.aventstack.extentreports.gherkin.model.*
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)

Usering version 3.1.1 and extentreports 3.1.5. Or do I need to configure something?

**Comment by foursyth** [comment]
Have you set the gherkin dialect to the correct language code?

**Comment by foursyth** [comment]
Oh, ignore my previous comment. I was looking at the subject. An asterisk I believe is not supported. What will an asterisk convert to?

**Comment by thomasdeurloo** [comment]
An asterisk can be used instead of Given, Then, When, And, But; to specify a step where the keyword is irrelevant. If i understand the above mentioned json file correctly that is also what is intended here with the asteriskses in every dialect, for example:
"en-pirate": {
    "and": [
      "* ",
      "Aye "
    ],
    "but": [
      "* ",
      "Avast! "
    ]

The asteriks does not necessarily have to convert into anything (if i understand your question right). It would be ok if it gets passed and parsed to the report as an asterisk. But indeed, it won't point to valid model in the report at the moment

**Comment by anshooarora** [comment]
Support for asterisk is added in version 4.0.1-SNAPSHOT. The release version will be available in a few days.

**Comment by thomasdeurloo** [comment]
Great!, thanks! i'll check it out.
