### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by brobee** [email2vimalraj/CucumberExtentReporter#71]
Hi, I got the following error and I'm pretty sure there should be some compatibility error. Which versions of cucumber-java/core/junit/extensreports is compatible? Or is it a bug? (Please note, I'm not able to use the brand new cucumber version, just older one.

[cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ExtentHtmlReporter

	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:114)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:245)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:291)
	at com.sun.proxy.$Proxy18.uri(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.uri(JUnitReporter.java:179)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:68)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)](url)

Here are my pom.xml:

```
<dependencies>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>1.2.5</version>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.5</version>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-jvm-deps</artifactId>
            <version>1.0.5</version>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.5</version>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-html</artifactId>
            <version>0.2.3</version>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>gherkin</artifactId>
            <version>2.12.2</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>2.42.2</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.8</version>
        </dependency>

        <dependency>
            <groupId>com.sybase</groupId>
            <artifactId>jconnect</artifactId>
            <version>6.5</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-swing-junit</artifactId>
            <version>3.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>

        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>1.2.0</version>
        </dependency>


        <!--REPORTING -->
        <dependency>
            <groupId>com.googlecode.totallylazy</groupId>
            <artifactId>totallylazy</artifactId>
            <version>1.20</version>
        </dependency>
           <dependency>
               <groupId>net.masterthought</groupId>
               <artifactId>cucumber-reporting</artifactId>
               <version>0.0.24</version>
           </dependency>
           <dependency>
               <groupId>com.google.guava</groupId>
               <artifactId>guava</artifactId>
               <version>16.0.1</version>
           </dependency>
           <dependency>
               <groupId>com.jayway.restassured</groupId>
               <artifactId>rest-assured</artifactId>
               <version>2.4.1</version>
           </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.8.3</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.vimalselvam</groupId>
            <artifactId>cucumber-extentsreport</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.relevantcodes</groupId>
            <artifactId>extentreports</artifactId>
            <version>2.41.2</version>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.27-incubating</version>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.20.1</version>
        </dependency>
```
Thank you in advance.

**Comment by email2vimalraj** [comment]
As mentioned in the doc, the extentreport dependency has to be added explicitly. Please refer here https://github.com/email2vimalraj/CucumberExtentReporter#usage.

**Comment by ruslank777** [comment]
Hi 
I am getting the same error even with the mentioned above dependency.
Here is an example with dependency:
`dependencies {
        compile 'com.codeborne:selenide:5.2.4'
        compile 'info.cukes:cucumber-java:1.2.5'

        compile group: 'org.testng', name: 'testng', version: '6.14.3'
        compile group: 'info.cukes', name: 'cucumber-testng', version: '1.2.5'
        //Extent Report
        compile group: 'com.aventstack', name: 'extentreports', version: '4.0.9'
        compile group: 'com.vimalselvam', name: 'cucumber-extentsreport', version: '3.1.1'`
For some reason when I am openeing the ExtentCucumberFormatter.java it is showing me that:
![image](https://user-images.githubusercontent.com/33557128/62970868-108f7980-bdd6-11e9-94b8-6a323477cae5.png)

And when I am trying to extend this formatter I am getting that error. Do you have any insights on that? thank you.
