### ISSUE TITLE
Issue with Gradle and Extent Report

### ISSUE THREAD

**Issue by dipakbachhav** [email2vimalraj/CucumberExtentReporter#81]
Hi VimalRaj,

I am using cucumber ,serenity-bdd with gradle below is the build.gradle file. I tried all option & still  facing below issue. Kindly help me to resolve my issue on priority basis because i want to give demo to my manager on tuesday with proper reorting.

Please Help me & sorry for inconvenience. 

```
 testCompile(
            'net.serenity-bdd:serenity-core:1.8.6',
            'net.serenity-bdd:serenity-junit:1.8.6',
            'net.serenity-bdd:serenity-cucumber:1.6.7',
            'net.serenity-bdd:serenity-report-resources:1.8.6',
            'net.serenity-bdd:serenity-screenplay-webdriver:1.8.6',
            'org.assertj:assertj-core:3.8.0',
            'io.codearte.jfairy:jfairy:0.5.9',
            'ch.qos.logback:logback-classic:1.2.3',
            'io.rest-assured:json-path:3.0.0',
            'io.rest-assured:rest-assured:3.0.0',
            'io.rest-assured:xml-path:3.0.0',
            'info.cukes:gherkin:2.12.2'
           
```

```
cucumber.runtime.CucumberException: Couldn't load plugin class: com.cucumber.listener.ExtentCucumberFormatter. It does not implement cucumber.api.Plugin
	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:179)
	at cucumber.runtime.formatter.PluginFactory.pluginClass(PluginFactory.java:166)
	at cucumber.runtime.formatter.PluginFactory.getPluginClass(PluginFactory.java:223)
	at cucumber.runtime.formatter.PluginFactory.isFormatterName(PluginFactory.java:201)
	at cucumber.runtime.RuntimeOptionsFactory.addPlugins(RuntimeOptionsFactory.java:94)
	at cucumber.runtime.RuntimeOptionsFactory.buildArgsFromOptions(RuntimeOptionsFactory.java:41)
	at cucumber.runtime.RuntimeOptionsFactory.create(RuntimeOptionsFactory.java:26)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.junit.internal.requests.SortingRequest.getRunner(SortingRequest.java:21)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by Udhay1316** [comment]
@dipakbachhav  - Hi I am also facing the similar issue. Did you resolve this issue ? I would like to hear your inputs from you
