### ISSUE TITLE
Extent Report not working with Cucumber JVM Parallel Plugin

### ISSUE THREAD

**Issue by Priya3001** [email2vimalraj/CucumberExtentReporter#87]
I had made all necessary changes for extent report in Runner class. Also, added dependencies for the same in pom.xml.

Since, I am also using parallel plugin, I also added following information in configuration of cucumber-jvm-parallel-plugin  in pom.xml:
<plugins>
 <plugin>
 <name>com.cucumber.listener.ExtentCucumberFormatter</name>
  <extension>html</extension>
  <outputDirectory>${project.build.directory}/cucumber-parallel/cucumber-extent-report</outputDirectory>
  </plugin>
  </plugins>

It is now generating extent report at  target/cucumber-parallel/cucumber-extent-report. But this report does not contain information which we are adding using Reporter.setSystemInfo in Runner class.

could you pleas help me solving this problem.

**Comment by email2vimalraj** [comment]
@Priya3001 : I'll look into this issue and fix if there is an issue.

**Comment by ashokkumarg** [comment]
@Priya3001 The runner files will be generated dynamically and how do we insert the Extent report codes in @BeforeClass and @AfterClass

**Comment by email2vimalraj** [comment]
@ashokkumarg : You will have to write a velocity template and config in the cucumber jvm parallel plugin.

Refer:
_Velocity template_: https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/extents-report/src/test/resources/cucumber-extents-report-runner.java.vm

_pom.xml for configuration_: https://github.com/temyers/cucumber-jvm-parallel-plugin/blob/master/src/it/junit/extents-report/pom.xml

_Full source code_: https://github.com/temyers/cucumber-jvm-parallel-plugin/tree/master/src/it/junit/extents-report

**Comment by ashokkumarg** [comment]
I will look in to this and get back to you @email2vimalraj

**Comment by ashokkumarg** [comment]
@email2vimalraj 

I have configured the things and it created the following dynamic test runner

```
package $packageName;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

import com.cucumber.listener.ExtentProperties;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import com.cucumber.listener.Reporter;

import java.io.File;

@RunWith(Cucumber.class)
@CucumberOptions(
        strict = true,
        features = {"C:/Users/MSTEMP/IdeaProjects/Cucumber/src/test/java/features/applicationform.feature:8"},
        plugin = {"[com.cucumber.listener.ExtentCucumberFormatter:C:/Users/MSTEMP/IdeaProjects/Cucumber/target/cucumber-parallel/1.html, json:C:/Users/MSTEMP/IdeaProjects/Cucumber/target/cucumber-parallel/1.json, html:C:/Users/MSTEMP/IdeaProjects/Cucumber/target/cucumber-parallel/1]"},
        monochrome = true,
        tags = ("[@Smoke]"),
        glue = ("[steps]"))
public class Applicationform01IT {

    @BeforeClass
    public static void beforeClass(){
      ExtentProperties extentProperties = ExtentProperties.INSTANCE;
                extentProperties.setReportPath("report.html");
    }

    @AfterClass
    public static void afterClass(){
      Reporter.loadXMLConfig(new File("src/test/resources/extent-config.xml"));
      Reporter.setSystemInfo("user", System.getProperty("user.name"));
      Reporter.setSystemInfo("os", "Windows");
    }
}
```

When I execute with mvn verify It is not executing anything and only displaying the following thing in console

> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.277 s - in $packageName.Applicationform01IT

When I execute the dynamically created runner file by right click --> Run as feature file.
I get this error

```
cucumber.runtime.CucumberException: Couldn't load plugin class: [com.cucumber.listener.ExtentCucumberFormatter

	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:175)
	at cucumber.runtime.formatter.PluginFactory.pluginClass(PluginFactory.java:165)
	at cucumber.runtime.formatter.PluginFactory.getPluginClass(PluginFactory.java:226)
	at cucumber.runtime.formatter.PluginFactory.isFormatterName(PluginFactory.java:195)
	at cucumber.runtime.RuntimeOptionsFactory.addPlugins(RuntimeOptionsFactory.java:90)
	at cucumber.runtime.RuntimeOptionsFactory.buildArgsFromOptions(RuntimeOptionsFactory.java:37)
	at cucumber.runtime.RuntimeOptionsFactory.create(RuntimeOptionsFactory.java:24)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:55)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:96)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: [com.cucumber.listener.ExtentCucumberFormatter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:173)
	... 26 more

```
If I configure the plugin, glue, steps perfectly I hope the code will work perfectly.

Could you suggest some ideas!

**Comment by ashokkumarg** [comment]
@email2vimalraj I get the null pointer exception under @AfterClass

`      Reporter.loadXMLConfig(new File("src/test/java/resources/extent-config.xml"));`

This is the dynamically created runner class

```
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

import com.cucumber.listener.ExtentProperties;
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import com.cucumber.listener.Reporter;

import java.io.File;

@RunWith(Cucumber.class)
@CucumberOptions(
        strict = true,
        features = {"C:/Users/MSTEMP/IdeaProjects/Cucumber/src/test/java/features/applicationform.feature:8"},
        plugin = {},
        monochrome = true,
        glue = {})
public class Applicationform01IT {

    @BeforeClass
    public static void beforeClass(){

    }

    @AfterClass
    public static void afterClass(){
      Reporter.loadXMLConfig(new File("src/test/java/resources/extent-config.xml"));
      Reporter.setSystemInfo("user", System.getProperty("user.name"));
      Reporter.setSystemInfo("os", "Windows");
    }
}
```

**Comment by Priya3001** [comment]
@email2vimalraj <https://github.com/email2vimalraj> : any update on this
extent report issue?

**Comment by ashokkumarg** [comment]
@Priya3001 He told it will be fixed on the cucumber extent report upcoming release. Waiting for the release date.

**Comment by FranAguiar** [comment]
Any update?

**Comment by Priya3001** [comment]
@email2vimalraj <https://github.com/email2vimalraj> : any update on this
extent report issue?
