### ISSUE TITLE
Extent Report Throwing an exception. However if i remove extent plugin it executes fine with regular cucumber

### ISSUE THREAD

**Issue by Zeinepka** [email2vimalraj/CucumberExtentReporter#95]
cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: freemarker/template/TemplateModelException
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:114)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:245)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:291)
	at com.sun.proxy.$Proxy14.done(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.done(JUnitReporter.java:227)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:101)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.NoClassDefFoundError: freemarker/template/TemplateModelException
	at com.cucumber.listener.ExtentCucumberFormatter.setExtentHtmlReport(ExtentCucumberFormatter.java:51)
	at com.cucumber.listener.ExtentCucumberFormatter.<init>(ExtentCucumberFormatter.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:107)
	... 12 more
Caused by: java.lang.ClassNotFoundException: freemarker.template.TemplateModelException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

**Comment by email2vimalraj** [comment]
@Zeinepka : Kindly let me know the versions of CucumberExtentReporter and extentreports-java

**Comment by email2vimalraj** [comment]
@Zeinepka : Kindly re-open if you still face this issue.
