### ISSUE TITLE
Not able to run any scenario after implementing extent report - getting this error - cucumber.runtime.CucumberException: java.lang.NoSuchFieldError: VERSION_2_3_23

### ISSUE THREAD

**Issue by dchoub** [email2vimalraj/CucumberExtentReporter#96]
Dependency added in POM are:
<dependency>
			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		</dependency>
			
	<dependency>
    <groupId>com.vimalselvam</groupId>
    <artifactId>cucumber-extentsreport</artifactId>
    <version>3.0.2</version>
     </dependency>
	 
	<dependency>
		<groupId>com.aventstack</groupId>
		<artifactId>extentreports</artifactId>
		<version>3.1.5</version>
		<scope>provided</scope>
	</dependency>

		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>2.3.23</version>
		</dependency>

Added below after method in Test Runner class:
@RunWith(Cucumber.class)
@CucumberOptions(
plugin={"com.cucumber.listener.ExtentCucumberFormatter:output/report.html"},
features = {"src/test/resources/feature"},
glue ={"com.mindstrength.stepdefs"},
tags={"@Profile"}

)
public class RunTest  {
	@AfterClass
	public static void setup() {
        Reporter.loadXMLConfig(new File("src//test//resources//extent-config.xml"));
        Reporter.setSystemInfo("user", System.getProperty("user.name"));
        Reporter.setSystemInfo("os", "Mac OSX");
        Reporter.setTestRunnerOutput("Sample test runner output message");
    }

getting below error in console
cucumber.runtime.CucumberException: java.lang.NoSuchFieldError: VERSION_2_3_23
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:114)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:241)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:287)
	at com.sun.proxy.$Proxy14.uri(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.uri(JUnitReporter.java:160)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:68)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.NoSuchFieldError: VERSION_2_3_23
	at com.aventstack.extentreports.reporter.ExtentHtmlReporter.start(ExtentHtmlReporter.java:93)
	at com.aventstack.extentreports.Report.attach(Report.java:55)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.aventstack.extentreports.ExtentReports.attachReporter(ExtentReports.java:68)
	at com.cucumber.listener.ExtentCucumberFormatter.setExtentReport(ExtentCucumberFormatter.java:77)
	at com.cucumber.listener.ExtentCucumberFormatter.<init>(ExtentCucumberFormatter.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:107)
	... 22 more

**Comment by email2vimalraj** [comment]
As mentioned in the [README](https://github.com/email2vimalraj/CucumberExtentReporter#usage), the CucumberExtentReporter v3.0.2 supports ExtentReport from v3.1.1 only. Kindly upgrade your extent report version from v2.41.2 to the latest one. Thanks.

**Comment by dchoub** [comment]
I have already added 3.1.5 version which is latest so I dont think so version is the issues.

<dependency>
	<groupId>com.aventstack</groupId>
	<artifactId>extentreports</artifactId>
	<version>3.1.5</version>
	<scope>provided</scope>
</dependency>

**Comment by dchoub** [comment]
@email2vimalraj  I have posted the POM file in above comment

**Comment by email2vimalraj** [comment]
@dchoub : You have freemarker added in your dependency. It could be the reason for the exception you get as ExtentReport also have that dependency. Can you please remove the freemarker dependency and check.

**Comment by dchoub** [comment]
I already tried this but same error. tried again and error is same only

**Comment by email2vimalraj** [comment]
@dchoub : Unable to reproduce your issue. I'm able to successfully run exactly with your pom dependencies. Please find the attached example project.

[issue96.zip](https://github.com/email2vimalraj/CucumberExtentReporter/files/2157727/issue96.zip)

**Comment by dchoub** [comment]
I tested your project in my machine and its working fine.
I also re compiled my project and changed Runner class name from RunTest to test and run it using mvn test command and its successfully able to generate the report.

But when I am running using eclipse its still giving me same error but for your sample project its working perfectly fine. :(

**Comment by email2vimalraj** [comment]
Cool. That means Eclipse is playing a game with your Java class path. Check
your Eclipse settings. It is nothing to do with the class name.

On 05-Jul-2018 6:44 PM, "dchoub" <notifications@github.com> wrote:

I tested your project in my machine and its working fine.
I also re compiled my project and changed Runner class name from RunTest to
test and run it using mvn test command and its successfully able to
generate the report.

But when I am running using eclipse its still giving me same error but for
your sample project its working perfectly fine. :(

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/email2vimalraj/CucumberExtentReporter/issues/96#issuecomment-402717570>,
or mute the thread

**Comment by chiran1729** [comment]
> @dchoub : You have freemarker added in your dependency. It could be the reason for the exception you get as ExtentReport also have that dependency. Can you please remove the freemarker dependency and check.

Thank you so much. It helped me. :)
Cheers..!!

**Comment by ZeynepUsta** [comment]
> > @dchoub : You have freemarker added in your dependency. It could be the reason for the exception you get as ExtentReport also have that dependency. Can you please remove the freemarker dependency and check.
> 
> Thank you so much. It helped me. :)
> Cheers..!!

Helped me too! Thanks!
